### ISSUE TITLE
Vertical/horizontal bar charts

### ISSUE THREAD

**Issue by juanbrujo** [asciimoo/cssplot#16]
Sorry again, why 'bar charts' are vertical and 'horizontal bar charts' are defined as .vertical?

**Comment by asciimoo** [comment]
The current naming is a bit confusing, maybe a `bar-chart -> column-chart`, `vertical-chart -> bar-chart` rename would make more sense according to https://developers.google.com/chart/interactive/docs/gallery/columnchart and http://www.highcharts.com/docs/chart-and-series-types/chart-types

**Comment by asciimoo** [comment]
done: d9d9146
