### ISSUE TITLE
live demo

### ISSUE THREAD

**Issue by jmcbee** [asciimoo/cssplot#9]
hi, where's the live demo. i'm only seeing pictures.

**Comment by phuicy** [comment]
Yeah, a github.io example would really be great.

**Comment by asciimoo** [comment]
Available @ https://asciimoo.github.io/cssplot/

**Comment by phuicy** [comment]
Thats awesome, thank you for the fast response. If you put that as a link on your README.md that would be a really great selling point for your project, i think you could even do iframes (i think).

**Comment by jmcbee** [comment]
@asciimoo is it possible to animate each bar?
